const jobInfo = [
  {
    category: 'Administration',
    companyName: 'Wikan Personal Botnia AB',
    days: '6',
    id: '1',
    imgUrl: '/image/administration.png',
    jobTitle: 'Marknadsadministratör för Skellefteå Kraft',
    link: 'https://arbetsformedlingen.se/platsbanken/annonser/27330840',
    shortInfo:
      'Tjänsten som marknadsadministratör på Skellefteå Kraft är ledig. Som marknadsadministratör på Skellefteå Kraft kommer du att arbeta med olika marknadsföringsuppgifter. Ansökan för marknadsadministratörstjänsten på Skellefteå Kraft är öppen.',
    type: 'Heltid',
  },
  {
    category: 'Administration',
    companyName: 'Skellefteå kommun',
    days: '12',
    id: '2',
    imgUrl: '/image/teacher.png',
    jobTitle: 'Utbildningskoordinator, Yrkesutbildning',
    link: 'https://arbetsformedlingen.se/platsbanken/annonser/27306228',
    shortInfo:
      'Erfaren utbildningskoordinator sökes till yrkeshögskola. Tjänsten som utbildningskoordinator på yrkeshögskolan kräver gedigen erfarenhet. Som utbildningskoordinator på yrkeshögskolan ansvarar du för att planera och samordna olika utbildningsaktiviteter.',
    type: 'Heltid',
  },
  {
    category: 'Administration',
    companyName: 'Ikett Personalpartner AB',
    days: '15',
    id: '3',
    imgUrl: '/image/tekniker.png',
    jobTitle: 'Service Tekniker, Elektronik',
    link: 'https://arbetsformedlingen.se/platsbanken/annonser/27285500',
    shortInfo:
      'Erfaren elektronikservice tekniker sökes. Tjänsten som elektronikservice tekniker kräver lång erfarenhet inom området. Som elektronikservice tekniker ansvarar du för att diagnostisera och åtgärda problem med elektroniska system och utrustning.',
    type: 'Heltid',
  },
  {
    category: 'Administration',
    companyName: 'Praktiska Gymnasiet',
    days: '18',
    id: '4',
    imgUrl: '/image/teacher.png',
    jobTitle: 'Gymnasielärare - Yrkesämnen',
    link: 'https://arbetsformedlingen.se/platsbanken/annonser/27278916',
    shortInfo:
      'En erfaren gymnasie lärare inom yrkesämnen efterfrågas för att ta ansvar för undervisning och utbildning av elever på gymnasiet. Personen bör ha goda kunskaper inom sitt yrkesområde samt ha pedagogisk erfarenhet och förmåga att anpassa undervisningen efter olika elevers behov och förutsättningar.',
    type: 'Heltid',
  },
  {
    category: 'Administration',
    companyName: 'Församling Expeditionen',
    days: '18',
    id: '5',
    imgUrl: '/image/parishhost.png',
    jobTitle: 'Församlingsvärd',
    link: 'https://arbetsformedlingen.se/platsbanken/annonser/27275819',
    shortInfo:
      'En församlingsvärd med erfarenhet inom människovård och fastighetsunderhåll behövs för att ta hand om och stödja besökare och besökande grupper vid kyrkan. Personen bör ha kunskap om fastighetsunderhåll och dessutom vara en god lyssnare och stödjande individ.',
    type: 'Heltid',
  },
  {
    category: 'Administration',
    companyName: 'Församling Expeditionen',
    days: '18',
    id: '6',
    imgUrl: '/image/parishhost.png',
    jobTitle: 'Församlingsvärd',
    link: 'https://arbetsformedlingen.se/platsbanken/annonser/27275819',
    shortInfo:
      'En avdelningschef med erfarenhet inom interna tjänster söks för ett tillfälligt uppdrag. Personen ska ansvara för att leda och stödja avdelningen samt implementera strategier och säkerställa att interna tjänster utförs på ett effektivt sätt.',
    type: 'Heltid',
  },
  {
    category: 'Administration',
    companyName: 'Region Västerbotten, Intern service',
    days: '20',
    id: '7',
    imgUrl: '/image/sectionmanager.png',
    jobTitle: 'Avdelningschef för interna tjänster',
    link: 'https://arbetsformedlingen.se/platsbanken/annonser/27264445',
    shortInfo:
      'En avdelningschef med erfarenhet inom interna tjänster söks för ett tillfälligt uppdrag. Personen ska ansvara för att leda och stödja avdelningen samt implementera strategier och säkerställa att interna tjänster utförs på ett effektivt sätt.',
    type: 'Heltid',
  },
  {
    category: 'Administration',
    companyName: 'Skellefteå kommun - familjeomsorg',
    days: '20',
    id: '8',
    imgUrl: '/image/unitmanager.png',
    jobTitle: 'Enhetschef för individ- och familjeomsorg',
    link: 'https://arbetsformedlingen.se/platsbanken/annonser/27261362',
    shortInfo:
      'En enhetschef med erfarenhet inom individ- och familjevård eftersöks för att ansvara för en enhet inom socialtjänsten. Personen bör ha erfarenhet av att leda och stödja personal, samt ha goda kunskaper inom individ- och familjevård.',
    type: 'Heltid',
  },
  {
    category: 'Data/it',
    companyName: 'ASSA ABLOY Industrial Sverige AB',
    days: '22',
    id: '9',
    imgUrl: '/image/Ittechnician.png',
    jobTitle: 'Industritekniker i Skellefteå',
    link: 'https://arbetsformedlingen.se/platsbanken/annonser/27249075',
    shortInfo:
      'ASSA ABLOY söker en industritekniker i Skellefteå för att ansvara för driftsättning och underhåll av maskiner samt förbättring av produktionsprocesser. Personen bör ha utbildning och erfarenhet inom området.',
    type: 'Heltid',
  },
  {
    category: 'Data/it',
    companyName: 'Minnovation international AB',
    days: '56',
    id: '10',
    imgUrl: '/image/Ittechnician.png',
    jobTitle: 'IT-tekniker',
    link: 'https://arbetsformedlingen.se/platsbanken/annonser/27117962',
    shortInfo:
      'Minnovation har ett ledigt IT-jobb tillgängligt. Jobbet är öppet för sökande som har relevant kompetens inom IT. Intresserade sökande uppmanas att ansöka om jobbet hos Minnovation.',
    type: 'Heltid',
  },
  {
    category: 'Data/it',
    companyName: 'Skelleftea kommun',
    days: '11',
    id: '11',
    imgUrl: '/image/agileprojectmanager.png',
    jobTitle: 'Agil projektledare',
    link: 'https://arbetsformedlingen.se/platsbanken/annonser/27312792',
    shortInfo:
      'En projektledare efterfrågas för att leda projekt och uppgifter inom ett specifikt område eller inom en organisation. Personen bör ha goda ledarskaps- och kommunikationsfärdigheter samt kunna samarbeta effektivt med olika parter.',
    type: 'Heltid',
  },
  {
    category: 'Data/it',
    companyName: 'WeSkill AB',
    days: '144',
    id: '12',
    imgUrl: '/image/systemdev.png',
    jobTitle: 'Systemutvecklare',
    link: 'https://arbetsformedlingen.se/platsbanken/annonser/26752777',
    shortInfo:
      'WeSkill söker en senior C#-utvecklare för att hjälpa till att utveckla och förbättra företagets produkter. Personen bör ha relevant utbildning och erfarenhet av C#-programmering.',
    type: 'Heltid',
  },
  {
    category: 'Data/it',
    companyName: 'Veritaz',
    days: '14',
    id: '13',
    imgUrl: '/image/analysts.png',
    jobTitle: 'Kravanalytiker',
    link: 'https://arbetsformedlingen.se/platsbanken/annonser/27293234',
    shortInfo:
      'En kravanalytiker sökes för att arbeta med agila utvecklingsteam och projektorganisationer. Personen bör ha erfarenhet av att analysera krav och skapa lösningar.',
    type: 'Heltid',
  },
  {
    category: 'Data/it',
    companyName: 'Northvolt',
    days: '28',
    id: '14',
    imgUrl: '/image/it-support-site-manager.png',
    jobTitle: 'IT-support Site Manager',
    link: 'https://arbetsformedlingen.se/platsbanken/annonser/27181338',
    shortInfo:
      'Hos Northvolt blir du inte bara en anställd utan också en del av ett snabbväxande företag med hög energi och en dynamisk miljö. Detta innebär att du kommer att få möjlighet att utvecklas tillsammans med företaget och att du kommer att vara en del av en arbetsplats där det alltid händer något nytt och spännande.',
    type: 'Deltid',
  },
  {
    category: 'Data/it',
    companyName: 'Sogeti',
    days: '74',
    id: '15',
    imgUrl: '/image/systemdeveloper.png',
    jobTitle: 'Systemutvecklare',
    link: 'https://arbetsformedlingen.se/platsbanken/annonser/27017861',
    shortInfo:
      'På Sogeti kan du förvänta dig spännande och utmanande uppdrag inom olika branscher. Vi strävar efter att utveckla dina färdigheter och ge dig möjlighet att växa som professionell. Välkommen till en dynamisk och utvecklande arbetsplats!',
    type: 'Heltid',
  },
  {
    category: 'Data/it',
    companyName: 'Northvolt',
    days: '84',
    id: '16',
    imgUrl: '/image/master-data-specialist.png',
    jobTitle: 'Specialist inom Masterdata',
    link: 'https://arbetsformedlingen.se/platsbanken/annonser/26978137',
    shortInfo:
      'Hos Northvolt blir du inte bara en anställd utan också en del av ett snabbväxande företag med hög energi och en dynamisk miljö. Detta innebär att du kommer att få möjlighet att utvecklas tillsammans med företaget och att du kommer att vara en del av en arbetsplats där det alltid händer något nytt och spännande.',
    type: 'Heltid',
  },
  {
    category: 'Data/it',
    companyName: 'WeSkill AB',
    days: '12',
    id: '17',
    imgUrl: '/image/c++-developer.png',
    jobTitle: 'C++-utvecklare',
    link: 'https://arbetsformedlingen.se/platsbanken/annonser/27304270',
    shortInfo:
      'Northvolt är en arbetsplats som erbjuder en hög energinivå och en dynamisk miljö för sina anställda. Företaget är också snabbt växande, vilket innebär att du kommer att ha möjlighet att utvecklas och göra skillnad under din tid där. Att vara en del av Northvolt är en chans att vara med och bidra till en mer hållbar framtid.',
    type: 'Heltid',
  },
  {
    category: 'Transport',
    companyName: 'Postnord',
    days: '7',
    id: '18',
    imgUrl: '/image/mailman.png',
    jobTitle: 'Brevbärare',
    link: 'https://arbetsformedlingen.se/platsbanken/annonser/27323637',
    shortInfo:
      'Som brevbärare hos oss på Postnord är du en viktig del av vår verksamhet. Vi är ett företag som ständigt förändras med världen runt omkring oss, men vår sociala mission är densamma idag som igår. Du kommer att spela en avgörande roll i att säkerställa att brev och paket levereras på ett säkert och pålitligt sätt, och att människor runt omkring i landet kan kommunicera och handla med varandra.',
    type: 'Deltid',
  },
  {
    category: 'Transport',
    companyName: 'Postnord',
    days: '13',
    id: '19',
    imgUrl: '/image/truckdriver.png',
    jobTitle: 'Lastbilschaufför',
    link: 'https://arbetsformedlingen.se/platsbanken/annonser/27295965',
    shortInfo:
      'Som lastbilschaufför är du pulsen i allt vi gör här på transportföretaget. Vi vet att världen runt omkring oss ständigt förändras, men vår mission är densamma idag som igår - att säkerställa att varor transporteras på ett säkert och pålitligt sätt. Som lastbilschaufför kommer du att ha en nyckelroll i att se till att varor levereras på rätt tid och plats, och att företag runt omkring i landet kan fortsätta att verka.',
    type: 'Heltid',
  },
  {
    category: 'Transport',
    companyName: 'Konsultia',
    days: '13',
    id: '20',
    imgUrl: '/image/warehouse_worker.png',
    jobTitle: 'Lagerarbetare',
    link: 'https://arbetsformedlingen.se/platsbanken/annonser/27229892',
    shortInfo:
      'Svensk Cater söker för närvarande efter personal till våra kommande sommaruppdrag. Vi är ett företag som specialiserar sig på catering till evenemang och fester, och vi söker nu efter passionerade och entusiastiska människor som vill vara med och bidra till att skapa minnesvärda upplevelser för våra kunder.',
    type: 'Heltid',
  },
  {
    category: 'Transport',
    companyName: 'OnePartnerGroup Skellefteå AB',
    days: '35',
    id: '21',
    imgUrl: '/image/tyrefitter.png',
    jobTitle: 'Däckmontör',
    link: 'https://arbetsformedlingen.se/platsbanken/annonser/27201280',
    shortInfo:
      'Vi söker för närvarande efter ett antal däckmontörer till vår kund Däckia i Skellefteå. Som däckmontör kommer du att ha en viktig roll i att se till att fordonen är säkra och redo för alla väderförhållanden. Du kommer att arbeta i ett team av erfarna montörer och ha möjlighet att utveckla din kompetens inom området.',
    type: 'Heltid',
  },
  {
    category: 'Transport',
    companyName: 'Connect Bus',
    days: '35',
    id: '22',
    imgUrl: '/image/bus_driver.png',
    jobTitle: 'Bussförare',
    link: 'https://arbetsformedlingen.se/platsbanken/annonser/27258655',
    shortInfo:
      'Som bussförare hos Connect Bus kommer du att vara en del av ett av Nordens ledande bussföretag som ständigt växer. Vi söker nu efter drivna och passionerade människor som vill vara med och bidra till vår fortsatta framgång. Vi strävar efter att skapa en miljö där våra anställda kan växa och utvecklas tillsammans med oss.',
    type: 'Heltid',
  },
  {
    category: 'Transport',
    companyName: 'Oskarsson & Nilsson Åkeri AB',
    days: '8',
    id: '23',
    imgUrl: '/image/milkman.png',
    jobTitle: 'Mjölkleverantör',
    link: 'https://arbetsformedlingen.se/platsbanken/annonser/27305920',
    shortInfo:
      'Vi på företaget söker nu efter en förare till våra mjölkbilar i Umeå. Arbetet innebär transport av mjölk till både Umeå och Burträsk Mejeri. Om du har erfarenhet inom området och gillar att köra lastbil, kan detta vara en spännande möjlighet för dig.',
    type: 'Heltid',
  },
  {
    category: 'Transport',
    companyName: 'StudentConsulting',
    days: '8',
    id: '24',
    imgUrl: '/image/terminal-worker.png',
    jobTitle: 'Terminalarbetare',
    link: 'https://arbetsformedlingen.se/platsbanken/annonser/27325699',
    shortInfo:
      'Letar du efter ett extrajobb? Då kan du vara intresserad av att höra att vi söker efter terminalarbetare till ett av Sveriges största företag inom transport och distribution. Ta chansen att bli en del av vår team och utveckla din karriär samtidigt som du får möjlighet att arbeta inom en spännande och växande bransch.',
    type: 'Heltid',
  },
  {
    category: 'Transport',
    companyName: 'Blomsterlandet',
    days: '13',
    id: '25',
    imgUrl: '/image/warehouse_worker.png',
    jobTitle: 'Lagerarbetare',
    link: 'https://arbetsformedlingen.se/platsbanken/annonser/27299227',
    shortInfo:
      'Blomsterlandet i Skellefteå söker efter en lagerarbetare som har erfarenhet av att köra truck och är fysiskt kapabel att hantera företagets lager och varor. Den sökande kommer att ha ansvar för att hantera och organisera företagets lagringsutrymme samt lagerhantering och förberedelse av varor för försäljning. Personen behöver ha goda fysiska förmågor för att hantera tunga och skrymmande föremål.',
    type: 'Heltid',
  },
  {
    category: 'Transport',
    companyName: 'Blomsterlandet',
    days: '13',
    id: '26',
    imgUrl: '/image/warehouse_worker.png',
    jobTitle: 'Lagerarbetare',
    link: 'https://arbetsformedlingen.se/platsbanken/annonser/27299227',
    shortInfo:
      'Blomsterlandet i Skellefteå söker efter en lagerarbetare som har erfarenhet av att köra truck och är fysiskt kapabel att hantera företagets lager och varor. Den sökande kommer att ha ansvar för att hantera och organisera företagets lagringsutrymme samt lagerhantering och förberedelse av varor för försäljning. Personen behöver ha goda fysiska förmågor för att hantera tunga och skrymmande föremål.',
    type: 'Heltid',
  },
]

export default jobInfo
