const jobInfo = [
  {
    number: '1',
    image: '/./image/Swipekort_1.png',
    rubrik: 'Skellefteå taxi',
    titel: 'Taxichaufför',
    info: 'Du är en serviceinriktad person som trivs med att möta och samarbeta med nya människor. Du sätter en stor heder i punktlighet och är stolt över att vara en duktig förare. Säkerheten för dina passagerare och dina medtrafikanter är självklart i första rummet när du planerar och genomför dina körningar. Både dina kollegor och de du möter i yrket skulle beskriva dig som en utåtriktad och lösningsorienterad person som inte tvekar att hjälpa till.',
    type: 'Deltid',
    days: '4',
    link: 'https://arbetsformedlingen.se/platsbanken/annonser?q=skellefte%C3%A5',
  },
  {
    number: '2',
    image: '/./image/Swipekort_2.png',
    rubrik: 'Northvolt',
    titel: 'Gruppchef',
    info: 'Du är en serviceinriktad person som trivs med att möta och samarbeta med nya människor. Du sätter en stor heder i punktlighet och är stolt över att vara en duktig förare. Säkerheten för dina passagerare och dina medtrafikanter är självklart i första rummet när du planerar och genomför dina körningar. Både dina kollegor och de du möter i yrket skulle beskriva dig som en utåtriktad och lösningsorienterad person som inte tvekar att hjälpa till.',
    type: 'Heltid',
    days: '10',
    link: 'https://arbetsformedlingen.se/platsbanken/annonser?q=skellefte%C3%A5',
  },
  {
    number: '3',
    image: '/./image/Swipekort_3.png',
    rubrik: 'Skellefteå Lasarett',
    titel: 'Sjuksköterska',
    info: 'Du är en serviceinriktad person som trivs med att möta och samarbeta med nya människor. Du sätter en stor heder i punktlighet och är stolt över att vara en duktig förare. Säkerheten för dina passagerare och dina medtrafikanter är självklart i första rummet när du planerar och genomför dina körningar. Både dina kollegor och de du möter i yrket skulle beskriva dig som en utåtriktad och lösningsorienterad person som inte tvekar att hjälpa till.',
    type: 'Timanställning',
    days: '20',
    link: 'https://arbetsformedlingen.se/platsbanken/annonser?q=skellefte%C3%A5',
  },
  {
    number: '4',
    image: '/./image/Swipekort_5.png',
    rubrik: 'Skellefteå taxi',
    titel: 'Taxichaufför',
    info: 'Du är en serviceinriktad person som trivs med att möta och samarbeta med nya människor. Du sätter en stor heder i punktlighet och är stolt över att vara en duktig förare. Säkerheten för dina passagerare och dina medtrafikanter är självklart i första rummet när du planerar och genomför dina körningar. Både dina kollegor och de du möter i yrket skulle beskriva dig som en utåtriktad och lösningsorienterad person som inte tvekar att hjälpa till.',
    type: 'Heltid',
    days: '10',
    link: 'https://arbetsformedlingen.se/platsbanken/annonser?q=skellefte%C3%A5',
  },
  {
    number: '5',
    image: '/./image/Swipekort_4.png',
    rubrik: 'Skellefteå Kommun',
    titel: 'Förskolepedagog',
    info: 'Du är en serviceinriktad person som trivs med att möta och samarbeta med nya människor. Du sätter en stor heder i punktlighet och är stolt över att vara en duktig förare. Säkerheten för dina passagerare och dina medtrafikanter är självklart i första rummet när du planerar och genomför dina körningar. Både dina kollegor och de du möter i yrket skulle beskriva dig som en utåtriktad och lösningsorienterad person som inte tvekar att hjälpa till.',
    type: 'Deltid',
    days: '10',
    link: 'https://arbetsformedlingen.se/platsbanken/annonser?q=skellefte%C3%A5',
  },
  {
    number: '6',
    image: '/./image/Swipekort_3.png',
    rubrik: 'Swecon',
    titel: 'Servicetekniker',
    info: 'Du är en serviceinriktad person som trivs med att möta och samarbeta med nya människor. Du sätter en stor heder i punktlighet och är stolt över att vara en duktig förare. Säkerheten för dina passagerare och dina medtrafikanter är självklart i första rummet när du planerar och genomför dina körningar. Både dina kollegor och de du möter i yrket skulle beskriva dig som en utåtriktad och lösningsorienterad person som inte tvekar att hjälpa till.',
    type: 'Heltid',
    days: '10',
    link: 'https://arbetsformedlingen.se/platsbanken/annonser?q=skellefte%C3%A5',
  },
  {
    number: '7',
    image: '/./image/Swipekort_4.png',
    rubrik: 'Skellefteå Kommun',
    titel: 'Förskolepedagog',
    info: 'Du är en serviceinriktad person som trivs med att möta och samarbeta med nya människor. Du sätter en stor heder i punktlighet och är stolt över att vara en duktig förare. Säkerheten för dina passagerare och dina medtrafikanter är självklart i första rummet när du planerar och genomför dina körningar. Både dina kollegor och de du möter i yrket skulle beskriva dig som en utåtriktad och lösningsorienterad person som inte tvekar att hjälpa till.',
    type: 'Deltid',
    days: '10',
    link: 'https://arbetsformedlingen.se/platsbanken/annonser?q=skellefte%C3%A5',
  },
  {
    number: '8',
    image: '/./image/Swipekort_2.png',
    rubrik: 'Skellefteå Fabrik',
    titel: 'Elektriker',
    info: 'Du är en serviceinriktad person som trivs med att möta och samarbeta med nya människor. Du sätter en stor heder i punktlighet och är stolt över att vara en duktig förare. Säkerheten för dina passagerare och dina medtrafikanter är självklart i första rummet när du planerar och genomför dina körningar. Både dina kollegor och de du möter i yrket skulle beskriva dig som en utåtriktad och lösningsorienterad person som inte tvekar att hjälpa till.',
    type: 'Deltid',
    days: '10',
    link: 'https://arbetsformedlingen.se/platsbanken/annonser?q=skellefte%C3%A5',
  },
]

export default jobInfo
