import './globals.css'
import { Inter, Inter } from 'next/font/google'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const inter = Inter ({
  subject:['latin'],
  variable: '--font-inter',
  weight: ['400', '500', '600', '700', '900'],
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
